# Don't edit this file!
# It is automatically updated after every release of https://github.com/alejandrohdezma/sbt-ci
# If you want to suggest a change, please open a PR or issue in that repository

name: Auto-rebase PRs

on:
  push:
    branches-ignore:
      - rebase-pull-request**
      - cherry-pick-rebase-pull-request**
  pull_request:
    types: [labeled]

jobs:
  auto-rebase:
    name: Auto rebase PRs
    runs-on: ubuntu-latest
    steps:
      - uses: Label305/AutoRebase@v0.1.5
        with:
          github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
