# Don't edit this file!
# It is automatically updated after every release of https://github.com/alejandrohdezma/sbt-ci
# If you want to suggest a change, please open a PR or issue in that repository

name: Run Scala Steward on this repository

on:
  schedule:
    - cron: "0 5 * * 1,3,5"
  workflow_dispatch:

jobs:
  run-scala-steward:
    name: Run Scala Steward
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          ref: master
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3.0.2
        with:
          gpg-private-key: ${{ secrets.PGP_SECRET }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}
          git-user-signingkey: true
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          sign-commits: true
          author-email: ${{ steps.import_gpg.outputs.email }}
          author-name: ${{ steps.import_gpg.outputs.name }}
